name: Terraform Deployment

on:
  push:
    branches:
      - dev_branch
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code..
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform (use the latest version of Terraform)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # Install dependencies (e.g., install any other necessary tools)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      # Install Ruff
      - name: Install Ruff
        run: |
          pip install ruff

      # Run Ruff to check for issues in the code
      - name: Run Ruff
        run: |
         ruff check src/weather/weather_data_ingestion_function_unit_test.py
      - name: Run Ruff2
        run: |
         ruff check src/weather/weather_data_ingestion_function.py

      - name: Run Ruff3
        run: |
         ruff check src/data_process_function_unit_test.py

      - name: Run Ruff4
        run: |
         ruff check src/data_process_function.ipynb

      - name: Run Ruff5
        run: |
         ruff check src/scd_type_two_function_unit_test.py

      - name: Run Ruff6
        run: |
         ruff check src/scd_type_two_function.py


      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan 

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=dev"

        env:
          TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}

    #
