name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform (use the latest version of Terraform)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # Install dependencies (e.g., install any other necessary tools)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      - name: Terraform plan
        run: terraform plan 

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=prod"

        env:
          TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}

    #
